"""initial schema

Revision ID: 74174da01e54
Revises:
Create Date: 2026-02-15 14:27:54.524720

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74174da01e54"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("factors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_factors_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_factors_name"), ["name"], unique=False)

    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("strategy_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "factor_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("factor_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("percentile_rank", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["factor_id"],
            ["factors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("factor_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_factor_data_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_factor_data_factor_id"), ["factor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_factor_data_ticker"), ["ticker"], unique=False)

    op.create_table(
        "portfolio_holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_holdings")
    with op.batch_alter_table("factor_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_factor_data_ticker"))
        batch_op.drop_index(batch_op.f("ix_factor_data_factor_id"))
        batch_op.drop_index(batch_op.f("ix_factor_data_date"))

    op.drop_table("factor_data")
    op.drop_table("portfolios")
    with op.batch_alter_table("factors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_factors_name"))
        batch_op.drop_index(batch_op.f("ix_factors_category"))

    op.drop_table("factors")
    # ### end Alembic commands ###
