"""add backtest table

Revision ID: 6e8dbc4efa4c
Revises: 74174da01e54
Create Date: 2026-02-17 20:54:55.732877

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e8dbc4efa4c"
down_revision: Union[str, Sequence[str], None] = "74174da01e54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("strategy_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tickers", sa.JSON(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("rebalance_frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_id", sa.Integer(), nullable=False),
        sa.Column("total_return", sa.Float(), nullable=False),
        sa.Column("annualized_return", sa.Float(), nullable=False),
        sa.Column("annualized_volatility", sa.Float(), nullable=False),
        sa.Column("sharpe_ratio", sa.Float(), nullable=False),
        sa.Column("max_drawdown", sa.Float(), nullable=False),
        sa.Column("sortino_ratio", sa.Float(), nullable=False),
        sa.Column("calmar_ratio", sa.Float(), nullable=False),
        sa.Column("nav_series", sa.JSON(), nullable=True),
        sa.Column("returns_series", sa.JSON(), nullable=True),
        sa.Column("holdings_history", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backtest_results")
    op.drop_table("backtests")
    # ### end Alembic commands ###
